# Generated by Django 5.0.6 on 2024-07-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Task Label')),
                ('done', models.BooleanField(default=False)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
